### ISSUE TITLE
1.3.2 Meeting Minutes

### ISSUE THREAD

**Issue by kyusan93** [kyusan93/INF2001_P7-5#17]
To update minutes after attending kick off meeting with client.

**Comment by zchewwwww** [comment]
Meeting date: 4 Sep 2023 
Start time: 1530 End time 1600 
Present: Quah Chee Kwang (Client), Goh Thiam Aik, Li Peishan, Zoie Chew, Chiam Jooting, Claudia Chee Xin Lin
Absent: Nil


1. Requirements: Work allocation is assigned weekly every Monday and planning starts every Thursday of the week. All employees' availability must be informed in the system every Wednesday to be considered in planning . 

Team Question: Does this apply to holidays which falls on either Sunday or Monday or Thursday?

Client Response: Can assume there is no holiday as there will always be someone on duty.


2. Requirement: The staff should be able indicate their job preference for the week.

Team Question: What does "preference" means? Is it time or route?

Client Response: Give two options for preference. 1) By time slot, 2) By routes

3. Requirement: If employees miss the weekly deadline, requests will be dealt with on a case-by-case basis
The manager should be able to deal with requests by the staff that missed the weekly deadline on a case-by-case basis

Team Question: What if the staff misses the weekly deadline? What time is the cut-off on Wednesday?
Client Response: Fix it to 23:59 first, allowing managers to extend/dun extend. May want to have this feature. Able to make it a variable?


4. Requirement: The manager should be able to visualize the staff workload immediately on the landing page

Team Question: Should everyone have the same landing page?

Client Response: Staff only need to see what they need to see, the manager can see more things. Requires role-based privileges.

5.  Requirement: IT administrators will oversee adding new staff and managers to the system

Team Question: What role-based privileges do IT administrators require?
Client Response: Just give them basic features such as add, edit, and view


Overall Customer Requirement for the project: Focus more on workload and planning, allow the manager to have an oversight of things which is the main objective of the piece of software.

**Comment by kyusan93** [comment]
Completed
