### ISSUE TITLE
1.2.4 Prepare Questionnaire for Client

### ISSUE THREAD

**Issue by kyusan93** [kyusan93/INF2001_P7-5#2]
**Task Description: These are the questions posted to client and what is the client responses**
**Task Goal: To understand the requirements**
**Success Criteria: Able to get the exact requirements based on the questions posted**
**Allocated Time: 3 weeks**
**Start Date / End Date: Week 1 to 3**

1. The app should be Web-based in a language of your choosing
2. The manager should be able to visualise the staff workload immediately on the landing page
3. The manager should be able to allocate jobs to staff for one week at a time
4. The manager should be able to view up to three staff availability and any relevant information to make the job assignment easier on the job allocation page
5. When displaying the staff availability, the workload assigned, staff’s job preference, and availabilities for the week should be shown
6. On the landing page, the top three staff with the lowest workload should be shown, and highlight all staff over 40 hours of jobs allocated
7. Staff should be able to view their weekly job assignments and overall workload for the month on their landing page
8. Staff can add and edit their availabilities up to 5 weeks ahead of time.
9. Staff can indicate their job preference for the week
10. Staff can reject jobs assigned to them, but they will be warned to discuss the jobs with their manager before proceeding with the rejection
11. The company’s IT administrators will oversee adding new staff and managers to the system

**Possible Questions**
1. What are the overall main objective of the web-based application?
2. What issues are we currently facing and is trying to solve?
3. Should the app be responsive to different devices screen size? (Example, smartphones, laptop, iPad?)
4. How would you prefer the visualisation of staff workload be on landing page? (Example: graph? table?)
5. Is the landing page view with the top 3 lowest workload accessible to only managers via restricted views or made available to all?
6. What is considered lowest workload? Below how many hours?
7. If the staff rejects the job assigned the job, what is the impact and how will the job be reassigned to another staff?
8. What are the type of role based permission required for each individual users? (Manager, Staff , IT administrator)
9. What are the option if the employees missed the Wednesday deadline? Who do they contact or email?
10. What if the staff fall sick within the week? What should the staff do?

**Confirmed Questions** (refer to comments)

**Comment by SelenaxPS** [comment]
Requirement: Planes do not stay on the ground for more than three hours	
Question:  What if the plane is having technical issues and not able to take off within 3 hours?

Requirement: The app should be Web-based in a language of your choosing	
Question: 
1) Besides web programming language, is there any constraints on the 
a) System used (Linux/Windows)
b) Database (MySQL, MSSQL, Oracle, etc)
c) Brands and technical specs for all Servers and networking devices

**Requirement: Security**
Question: 
1) Need TLS for HTTP? If yes, 
a) any TLS version preference
b) any requirements on the key size and type (RSA 2048, RSA 4096, ECDSA 256, etc)
c) any requirements on the cipher suites
d) need any client/server authentication
2) Need to lock down client IP addresses.

**Requirement: High-Availability**
1) Need HA for all components (Web Servers, DB Servers, Network layer)
2) Need to load balance for all components (Same components as above)


**Requirement: Is there any relevant information to make job assignment easier on job allocation page for Managers**	
Question:
1) What is the relevant information required?


**Requirement: When displaying the staff availability, the following should be shown:**	
1) This is for which user?

**Requirement: Staff’s (Cabin Crew) job preference**	
Question:
1) What does "preference" mean? Is it time or route?

**Requirement: Availabilities for the week**
Question:
1) Need to show the availabilities for the week for all crews in one page or as a chart?

**Requirement: On the landing page (Manager view):**
Question:
1) This is for which user?

**Requirement: Can indicate their job preference for the week**
Question:
1) What does "preference" mean? Is it time or route?

**Requirement: Can reject jobs assigned to them, but they will be warned to discuss the jobs with their manager before proceeding with the rejection**
Question:
1) The rejection takes effect immediately after clicking okay on the warning or need Manager to approve before the crew can reject?
2) By which day can the crews reject their assigned jobs?

**Requirement: IT administrators will oversee adding new staff and managers to the system**
Question:
1) Anyone need to approve the addition of new crews or managers?
2) Do all managers have the rights to plan for all crews or is there groupings?

**Comment by kyusan93** [comment]
Completed
