### ISSUE TITLE
1.5.1 Introduction

### ISSUE THREAD

**Issue by kyusan93** [kyusan93/INF2001_P7-5#21]
Introduction section for M1 report.

**Comment by cordeliajt** [comment]
The problem of efficiently managing cabin crews’ workloads while fostering a good work-life balance has grown in importance in today's changing working environment. By creating a web-based workload management system specifically for the requirements of an airline cabin crew division, this project aims to address this complex workflow and requirements. The project's goal is to develop a potent tool that will improve workforce management, help cabin crews find a better work-life balance, and maximise cabin crews scheduling.

**Comment by kyusan93** [comment]
Completed
