### ISSUE TITLE
1.5.1.1 Product Scope

### ISSUE THREAD

**Issue by kyusan93** [kyusan93/INF2001_P7-5#22]
Product Scope for M1 report.

**Comment by claudmeow** [comment]
The main goal of this project is to create and put into use a comprehensive Workload Management System that fits easily with an airline cabin crew division's everyday operation. This method, which considers cabin crews preferences, ranks, flight requirements, and labour availability, will alter how cabin crews are assigned to flights. By doing this, it seeks to improve cabin crews' productivity, reduce disputes, and streamline the allocation process. 

 

The below highlights the benefits of the product: 

Work-Life Balance: By giving workers the option to declare their job preferences and availability, the product gives them more control over the tasks they are assigned, which promotes a better work-life balance. 

Workforce Efficiency: The product helps managers to allocate crews more wisely, resulting in optimal job assignments and higher workforce productivity. 

Insight: The product offers insight into the company's personnel situation through interactive dashboards, enabling improved planning and allocation tactics. 

Operational Excellence: The product enables proactive planning and reduces operational interruptions by enabling visualisation of cabin crews’ preferences and availability up to one month in advance. 

Data Security: The product places a strong emphasis on protecting sensitive employee data while also guaranteeing data privacy and regulatory compliance. 



You may find an in-depth analysis of the project's goals, features, and the needs essential for its realisation in this section. The user interface requirements, functional features for managers and cabin crews, non-functional needs like performance and security, use case diagram and descriptions, and extra project-specific requirements will all be covered in detail. Finally, we will discuss project management and estimation, detailing the strategy for carrying out the project. 



A thorough explanation of each component will be provided in the next parts of this paper, ensuring that the scope and goals of the project are understood in full.

**Comment by kyusan93** [comment]
Comlpeted
