### ISSUE TITLE
1.5.1.2 Related Background Literature

### ISSUE THREAD

**Issue by kyusan93** [kyusan93/INF2001_P7-5#23]
Related Background Literature for M1 report.

**Comment by SelenaxPS** [comment]
Work Life Balance 

Airline operators should consider the importance of adequate rest for adequate recovery and facilitating work-life balance to support employee health and well-being. Airline operators are also advised to consider the importance of business support, in the form of fatigue-related processes and resources, effective communication and commitment from management to cabin staff. tablets in general. 

 

Project Planning 

The success of any project is measured by  completion time, within budget, and by achieving planned activities based on the initial plan. Therefore, planning plays an important role in project success. To successfully complete all these projects, each project has to go through different stages, where the level of effort and impact on the success of the project  depends on each stage. Among the various stages of a project, project planning is one of the important stages [2].

**Comment by kyusan93** [comment]
Completed
