### ISSUE TITLE
1.5.1.4 References and Acknowledgements

### ISSUE THREAD

**Issue by kyusan93** [kyusan93/INF2001_P7-5#25]
References and Acknowledgements for M1 report.

**Comment by zchewwwww** [comment]
[1] 

M. J. VAN DEN BERG, T. L. SIGNAL, and P. H. GANDER, “Fatigue risk management for cabin crew: the importance of company support and sufficient rest for work-life balance—a qualitative study,” Industrial Health, vol. 58, no. 1, pp. 2–14, 2020, doi: https://doi.org/10.2486/indhealth.2018-0233. [Accessed: 15 September 2023] 

[2] 

T. Lemma, E. Berhan, and B. Beshah, “Ermias Tesfaye KEY PROJECT PLANNING PROCESSES AFFECTING PROJECT SUCCESS,” International Journal for Quality Research, vol. 11, no. 1, pp. 159–172, 2017, doi: https://doi.org/10.18421/IJQR11.01-10. [Accessed: 15 September 2023] 

‌

**Comment by kyusan93** [comment]
Completed
