### ISSUE TITLE
1.5.2.1 Product Overview

### ISSUE THREAD

**Issue by kyusan93** [kyusan93/INF2001_P7-5#27]
Product Overview for M1 report.

**Comment by claudmeow** [comment]
Product perspective 

The Workload Management System is a standalone web-based application specifically designed for an organisation's flight attendants. It is not a replacement for the existing system, but a new solution aimed at improving staff management and improving the work-life balance of crew members. This system is an integral part of the airline's operations, providing the necessary assistance in assigning flight attendants to flights. 

**System architecture diagram**
System architecture diagram illustrating the high-level components and interactions of the workload management system in the broader context of aeronautical operations. The main system components include: 


**Web display** 
This is the user-facing part of the system, which is accessible to both crew members and managers. It provides an interface for users to log in, view their assignments, assign preferences, and interact with the system. 


**Database** 
The database stores essential data including employee information, flight schedules, crew preferences and system logs. It serves as a central repository for all the information needed to assign and manage teams. 


**Crew allocator** 
This component is the heart of the system, responsible for optimising crew allocation on flights. It considers the crew's preferences, skills, flight requirements, and available human resources when making assignment decisions. Dashboards and reports: 
The system provides an interactive dashboard for crew members and managers, providing real-time visibility into workforce status, work assignments, and availability. Reporting tools facilitate data analysis and decision making. 


**Authentication and security** 
This component manages user authentication and ensures the security of sensitive data. It establishes trust in the system and protects user privacy. 


**External interface** 
The system can interact with external systems, such as personnel databases for employee information and flight planning systems for up-to-date flight data. These interfaces are important for data synchronisation and accuracy. 


In the context of airline operations, workload management systems play a central role in ensuring that assigned crews operate flights in an efficient, transparent, and employee-friendly manner. It aims to optimise workforce management, reduce scheduling conflicts, and ultimately contribute to a more balanced professional and personal experience for crew members.

**Comment by kyusan93** [comment]
Completed
