### ISSUE TITLE
1.5.2.2 Product Functionality

### ISSUE THREAD

**Issue by kyusan93** [kyusan93/INF2001_P7-5#28]
Product Functionality for M1 report.

**Comment by SelenaxPS** [comment]
PF1: The product shall allow the manager to visualize the staff workload immediately on the landing page 

PF2: The product shall allow the manager to allocate jobs to staff for one week at a time 

PF3: The product shall allow the manager to view up to three staff availability and any relevant information to make the job assignment easier on the job allocation page 

PF4: The product shall show the workload assigned, the staff’s job preference, and availabilities for the week when displaying the staff availability 

PF5: The product shall display the top three staff with the lowest workload should be shown, and highlight all staff over 40 hours of jobs allocated on the landing page 

PF6: The product shall allow staff to view their weekly job assignments and overall workload for the month on their landing page 

PF7: The product shall allow staff to add, edit, and remove their availability up to 5 weeks ahead of time 

PF8: The product shall allow staff to indicate their job preference for the week 

PF9: The product shall allow staff to reject jobs assigned to them, but will be alerted to discuss the job with their manager before proceeding with the rejection 

PF10: The product shall allow the company’s IT administrator to add new staff and managers to the management system 

PF11: The product shall allow the administrator, manager, and staff to login to the system

**Comment by SelenaxPS** [comment]
PF12: The product shall be a web-based, responsive application.

**Comment by kyusan93** [comment]
Completed
