### ISSUE TITLE
1.5.2.3 Assumptions and Dependencies

### ISSUE THREAD

**Issue by kyusan93** [kyusan93/INF2001_P7-5#29]
Assumptions and Dependencies for M1 report.

**Comment by zchewwwww** [comment]
**Assumptions** 

Our team made the following assumptions for product development: 

The software development will be done from scratch as well as the content of the software. The report is properly structured, covering our project planning, estimation and requirements achievement. 

The current process in place within the client’s company before system integration, requires manual process for team assignment leading to significant effort for Managers. 

To maintain system accuracy, it is assumed that information about work allocation and team availability is regularly updated and synchronised.   

The project shall be completed within the 12 weeks deadline given for the development of the product. 

The system will be able to inform the staff about the work allocation and a warning will be issued when the staff decides to reject a job. 

Staff interest and skills are accurately represented in the system for effective job allocation. 

The company will be operating 24/7 including any holidays 

There is more than one duty manager as the company operates 24/7 

 

 

Dependencies 

Our team has proposed to host our webpage using AWS on cloud. The reasoning behind this choice lies in AWS’s ability to provide a dependable, scalable and secure global computing infrastructure. AWS adopts a comprehensive strategy to ensure the safety and fortification of the entire infrastructure, covering physical, operational, and software aspects. Additionally, it presents a cost-efficient solution, as we will only be billed for the resources we utilize, without any need for long-term contracts or upfront commitments [3].

**Comment by kyusan93** [comment]
Completed
