### ISSUE TITLE
1.5.3.1 User Interface Requirements

### ISSUE THREAD

**Issue by kyusan93** [kyusan93/INF2001_P7-5#30]
User Interface Requirements for M1 report.

**Comment by SelenaxPS** [comment]
UIR1: The system shall have a login page for the manager, staff, and IT administrators 

UIR2: The system shall have a landing page for the managers 

UIR3: The system shall have a landing page for the staff 

UIR4: The system shall have a page for the managers to allocate workload 

UIR5: The system shall have a page for the IT administrators to add new staff/managers

**Comment by SelenaxPS** [comment]
UIR6: The system shall have a button to allow user to log out

**Comment by kyusan93** [comment]
Complete
