### ISSUE TITLE
1.5.3.2 Functional Requirements

### ISSUE THREAD

**Issue by kyusan93** [kyusan93/INF2001_P7-5#31]
Functional Requirements for M1 report.

**Comment by SelenaxPS** [comment]
FR1: The system shall allow the manager to assign work allocation weekly on every Monday 
 

FR2: The system shall allow the manager to plan workload allocation on every Thursday of the week 
 

FR3: The system shall allow the staff to inform their availabilities in the system every Wednesday for it to be considered in the planning 
 

FR4: The system shall allow the manager to deal with requests by the staff that missed the weekly deadline on a case-by-case basis 
 

FR5: The system shall allow the manager to assign the roster based on the plane assigned to a route 
 

FR6: The system shall allow the manager to assign one Chief Stewardess/Steward or higher and two Leading Stewardess/Steward or lower for Boeing 737-8 serving routes 
 

FR7: The system shall allow the manager to assign one In-Flight Supervisor, one Chief Stewardess/Steward, two Leading Stewardess/Steward, and four Flight Stewardess/Steward for Boeing 787-10 and Airbus A350-900 serving routes 
 

FR8: The system shall allow the manger to assign work allocation such that the staff does not need to travel between routes 
 

FR9: The system shall allow the manager to assign work allocation such that planes do not stay on the ground for more than three hours 
 

FR10: The system shall allow the manager to assign work allocation such that the staff should get at least 12 hours of rest after servicing for more than 10 hours 

 

FR11: The system shall allow the manager to visualise the staff workload immediately on the landing page 
 

FR12: The system shall allow the manager to allocate jobs to staff for one week at a time 
 

FR13: The system shall allow the manager to view up to three staff availabilities and relevant information to make the job assignment easier on the job allocation page 
 
FR14:  The system should allow the manager to view the workload assigned when displaying staff availability 
 
FR15:  The system should allow the manager to view the staff's job preference when displaying staff availability 
 
FR16:  The system should allow the manager to view the availabilities of the staff for the week when displaying staff availability 
 

FR17: The system shall allow the manager to view the top three staff with the lowest workload on the landing page 

 

FR18: The system shall allow the manager to view all staff that has more than 40 hours of jobs allocated on the landing page 

 
FR19: The system shall allow the staff to view their job assignments on the landing page 
 

FR20: The system shall allow the staff to view their overall workload for the month on the landing page 
 

FR21: The system shall allow the staff to add the availabilities up to 5 weeks ahead of time 
 

FR22: The system shall allow the staff to edit the availabilities up to 5 weeks ahead of time 
 

FR23: The system shall allow the staff to indicate their job preference for the week 
 

FR24: The system shall allow the staff to reject the jobs assigned to them but they will be warned to discuss the jobs with their manager before proceeding with the rejection 
 

FR25: The system shall allow the administrator to add new staff into the system on the admin landing page 

 

FR26: The system shall allow the administrator to add a new manager into the system on the admin landing page 

 

FR27: The system shall allow users to log in 

 

FR28: The system shall allow users to log out

**Comment by kyusan93** [comment]
Complete
