### ISSUE TITLE
1.5.3.3 Use Case Model

### ISSUE THREAD

**Issue by kyusan93** [kyusan93/INF2001_P7-5#32]
Use Case Model for M1 report.

**Comment by zchewwwww** [comment]
Draft 



![Image](https://github.com/kyusan93/INF2001_P7-5/assets/97510985/9950734f-636c-494c-af09-ffc02465c238)

**Comment by zchewwwww** [comment]
Final Diagram

![Image](https://github.com/kyusan93/INF2001_P7-5/assets/97510985/05f68f34-ce12-4fdc-8923-87cefc171cca)

**Comment by kyusan93** [comment]
Complete
