### ISSUE TITLE
1.5.3.4 Non-functional Requirements

### ISSUE THREAD

**Issue by kyusan93** [kyusan93/INF2001_P7-5#33]
Non-functional Requirements for M1 report.

**Comment by cordeliajt** [comment]
NFR1: The application should incorporate robust security measures, including 2-factor authentication (2FA). 

NFR2: The application should provide a user-friendly experience with intuitive navigation. 

NFR3: The application should have the capability to accommodate multiple languages. 

NFR4: The application should possess scalability, ensuring it can support a growing number of employees in the future. 

NFR5: The application should have a minimum uptime of 99.9% over a year, allowing for scheduled maintenance. 

NFR6: The application should not crash or produce critical errors under normal usage conditions. 

NFR7: The application should conform to WCAG (Web Content Accessibility Guidelines) standards to ensure accessibility for users with disabilities. 

NFR8: The application shall respond to user interactions within 2 seconds under standard load conditions.

**Comment by kyusan93** [comment]
Complete
