### ISSUE TITLE
1.5.5 Use Case Descriptions

### ISSUE THREAD

**Issue by kyusan93** [kyusan93/INF2001_P7-5#37]
Use Case Descriptions for M1 report.

**Comment by zchewwwww** [comment]
<html>
<body>


Use Case ID: | UC-1
-- | --
Use Case Name: | Allocate workload to staff
Description: | Manager will finalise the final work allocation planning for the week by Thursday 23:30
Primary Actor: | Manager
Preconditions: | Manager is logged into the system System must be connected and accessible to database The airline fleet consists of twenty Boeing 737-8, ten Boeing 787-10, and ten Airbus A350-900.  On all Boeing 737-8 serving routes, one Chief Stewardess/Steward or higher and two Leading Stewardess/Steward or lower must be assigned.  On all Boeing 787-10 and Airbus A350-900 serving routes, one In-Flight Supervisor, one Chief Stewardess/Steward, two Leading Stewardess/Steward, and four Flight Stewardess/Steward must be assigned.
Postconditions: | Manager can confirm the work allocation for the week and the system sends out the finalised schedule to the staff.
Main Success Scenarios: | The manager selects the route for assigning the weekly roster The manager selects the plane model that is available for the selected route The system presents a list of planes for the selected plane model, displaying their plane license number The manager selects the plane of choice and selects the staff allocation table The system returns the staff allocation table for the selected plane The manager selects the In-Flight Supervisor time slot The system displays the staff search with only staff with the rank of In-Flight Supervisor who are available and met the rest hours requirements  The manager selects the required number of staffs for the role of In-Flight Supervisor The system displays the staff allocation table for the selected plane with the updated In-Flight Supervisor name The manager selects the Chief steward/stewardess time slot The system displays the staff search with only staff with the rank of Chief steward/stewardess who are available and met the rest hours requirements  The manager selects the required number of staffs for the role of Chief steward/stewardess The system displays the staff allocation table for the selected plane with the updated Chief steward/stewardess name The manager selects the Leading steward/stewardess time slot The system displays the staff search with only staff with the rank of Lead steward/stewardess who are available and met the rest hours requirements  The manager selects the required number of staffs for the role of Lead steward/stewardess The system displays the staff allocation table for the selected plane with the updated Lead steward/stewardess name The manager selects the Flight steward/stewardess time slot The system displays the staff search with only staff with the rank of Flight steward/stewardess who are available and met the rest hours requirements  The manager selects the required number of staffs for the role of Flight steward/stewardess The system displays the staff allocation table for the selected plane with the updated Flight steward/stewardess name The manager submits the work allocation The system validates the submission and updates to the database The system displays a pop-up success message The system email the work allocation plan by Monday at 00:00
Alternative Scenarios: | 7a. Plane selected is Boeing 737-8 7a1. System will display BOTH In-Flight Supervisor AND Chief steward/stewardess who are available and met the rest hours requirements 7a2. The manager will select ONLY EITHER In-Flight Supervisor OR Chief steward/stewardess 7a3. Skip to Step 13 17a. Plane selected is Boeing 737-8 17a1. System will display BOTH Lead steward/stewardess AND Flight steward/stewardess who are available and met the rest hours requirements 17a2. The manager will select ONLY EITHER Lead steward/stewardess OR Flight steward/stewardess 17a3. Skip to Step 19 22a. The manager submits the work allocation, and the system detects an error that “No name was selected for the staff allocation” 22a1. The manager step 6, 8, 10 or 12 depending on the staff rank whose name not allocated


</body>
</html>

**Comment by kyusan93** [comment]
Completed
