### ISSUE TITLE
1.5.6 Data Dictionary

### ISSUE THREAD

**Issue by kyusan93** [kyusan93/INF2001_P7-5#38]
Data Dictionary for M1 report.

**Comment by claudmeow** [comment]
**User** 

User refers to the Manager, Staff, and IT Administrator. 

**System** 

System refers to the web application that the users are accessing.  

**Database** 

Database is used to store information of all users of the system. 

**Email Server** 

Email server is used to track staff rejection. 

**Staff** 

Staff refers to the cabin crew.

**Comment by kyusan93** [comment]
Complete
