### ISSUE TITLE
2.2.1 Class Diagram

### ISSUE THREAD

**Issue by kyusan93** [kyusan93/INF2001_P7-5#46]
Detailed design involves creating detailed specifications for individual system components or modules. It includes defining algorithms, data structures, and interfaces, among other things, to guide the implementation phase.

**Comment by SelenaxPS** [comment]
As seen from the class diagram above, the control "UserManagement" consist of the boundary "LoginUI" and "Logout UI". The "UserManagemnet" Control uses the "User" Entity which contains the getter and setter methods.  

 

Meanwhile the Control "WorkloadManagement" uses the "StaffPreference" entity to retrieve staff preferences, ranks and availabilities. It also uses the Control "FlightManagement" which uses the Entity "Routes" and "Flights". 

 

The "Routes" Entity contains the getter, setter methods and attributes which includes the route_id, route_details and route_dates which the "Flights" Entity contains the getter, setter methods and attribute which includes the flight_id, flight_model, flight_staff_required. This information will be retrieved and displayed through the FlightManagement. 

 

For the "Dashboard" Boundary, this will display all the information required and viewed on the "Dashboard" by the Manager and Staffs.

**Comment by SelenaxPS** [comment]
![Image](https://github.com/kyusan93/INF2001_P7-5/assets/50551855/5f08d6d9-f41e-4bb7-8330-e54d84a39ed7)

**Comment by kyusan93** [comment]
Completed
