### ISSUE TITLE
2.2.2 Sequence Diagram

### ISSUE THREAD

**Issue by kyusan93** [kyusan93/INF2001_P7-5#47]
A sequence diagram is another UML diagram that illustrates the interactions and communication between objects or components in a system over time. It helps visualize the flow of messages and events between different parts of the system.

**Comment by zchewwwww** [comment]
![Image](https://github.com/kyusan93/INF2001_P7-5/assets/97510985/8049e241-5a8d-406e-aa40-4d8137d1a472)

Based on Figure 3, the “Manager” actor will first navigate to the “Add Workload” tab. The request will be passed from the “WorkloadAllocationPage” to the “WorkloadManagement” control and using the “getPlaneRoutes()” method, it will fetch the data from the database to retrieve all the routes and return the data through the same path and display it to the actor using the “displayPlaneRoutes()” method.  

 

Next, the “Manager” actor will select a route. The request will be passed from the “WorkloadAllocationPage” to the “WorkloadManagement” control and using the “getRouteDetails()” method, it will fetch the data from the database to retrieve the route details of the selected route and return the data through the same path and display it to the actor using the “displayRouteDetails()” method.  

 

When the “Manager” actor selects a flight, a request will be passed from the “WorkloadAllocationPage” to the “WorkloadManagement” control. Then using the “getCurrentAllocationStatus()” method, the request will be sent to the database and the details of the current allocated staff will be retrieved and the data is returned through the same path and displayed to the user using the “displayAllocationStatus()” method.  

 

Next, the “Manager” actor will click on Allocation Status not assigned slot. The request will be passed from the “WorkAllocationPage” control. Then using the “getRequiredStaffMember()” method, the request will be sent to the database and the details of the available staff will be retrieved and the data is returned through the same path and displayed to the actor using ”displayAvailableStaff()” method. 

 

When the “Manager” actor selects the staff he/she wishes to add, a request will be sent from the “WorkloadAllocationPage” to the “WorkloadManagement” control. Using the “updateAllocationStatusBar()” method, the allocation status bar will be updated with the corresponding colour of the selected staff and is displayed back to the user using “displayUpdatedStatusBar()”.  

 

If the “Manager” actor selects less than or equal to the number of required staff, he/she can proceed to the next step else an error message will be prompted to the user using the “displayError()”. 
 
The manager can choose to “Confirm” or “Cancel”, if the actor chose to confirm, he/she could proceed to the next step, else if they chose to cancel, they will be redirected to the previous selection page. 

 

If the “Manager” actor choses to save the selected staff, a request will be sent from the “WorkAllocation Page” to the “Workload Management” control. Using the “updateAllocationStatus()” method, the request will be sent to the database to update the allocation status. The data is then returned through the same path and the allocation status bar will be updated with the corresponding colour of the selected staff and is displayed back to the user and a success message will be prompted using “displaySuccessMessage()”. 

 

If the “Manager” actor choses to “Back”, they will be redirected to workallocation page. 

 

Once all the above steps are completed, a request will be sent to the SMS server to send an SMS to notify the staff of their allocation.

**Comment by zchewwwww** [comment]
![Image](https://github.com/kyusan93/INF2001_P7-5/assets/97510985/12864a46-ea98-4b0a-b9d3-6622b45bff62)

Based on Figure 4, the “Staff” actor will first navigate to the “Add Job Preference” tab. The request will be passed from the “PreferencePage” to the “ManagePreferences” control and using the “getStaffAvailability()” method, it will fetch the data from the database to retrieve the “Staff” actor’s job preference and return the data through the same path and display it to the actor using the “displayStaffPreferedRoute()” method.  

 

Next, the “Staff” actor will click on “Set Preference”. The request will be passed from the “PreferencePage” to the “ManagePreferences” Control and using the “getStaffPreferredRoute()” method, it will fetch the data from the database to retrieve the available routes for the staff to select and return the data through the same path and display it to the actor using the “displayStaffPreferredRoute()” method.  

 
Once the “Staff” actor selects a route and click “Confirm”, the request will be passed from the “PreferencePage” to the “ManagePreferences” Control. Using the “setStaffPreferredRoute()” method, the request will then be passed to the database to update the “Staff” actor’s selected preference and the data will be returned through the same path and displayed to the actor using the “displayStaffPreferredRoute()” method.

**Comment by kyusan93** [comment]
Completed
