### ISSUE TITLE
2.3 Updated Use Case Diagram and Use Case Descriptions

### ISSUE THREAD

**Issue by kyusan93** [kyusan93/INF2001_P7-5#48]
Port over from M1 and updated with changes.

**Comment by claudmeow** [comment]
Use Case Diagram draft 

![Image](https://github.com/kyusan93/INF2001_P7-5/assets/108879146/915e6984-bca9-4ae3-ab84-db7cac84c240)

**Comment by claudmeow** [comment]
Use Case Diagram



![Image](https://github.com/kyusan93/INF2001_P7-5/assets/108879146/0c430912-eb68-4c04-b2f5-48649a449994)

**Comment by kyusan93** [comment]
Completed
