### ISSUE TITLE
3.1 Prototype

### ISSUE THREAD

**Issue by kyusan93** [kyusan93/INF2001_P7-5#50]
A prototype is a working model of a software system or a specific feature. It is used to visualize and test ideas before committing to full-scale development, allowing stakeholders to provide feedback and refine requirements.

**Comment by zchewwwww** [comment]
**Manager**
1. The “Manager” will login and select the role “Manager”

![Image](https://github.com/kyusan93/INF2001_P7-5/assets/97510985/6fdc2598-6f25-4d41-8d0e-e2baa73778e0)


2. It then redirects to the Manager login page.
![Image](https://github.com/kyusan93/INF2001_P7-5/assets/97510985/448e30f1-e7ea-42f2-93a5-bc745f3ac150)

3. Upon logging in, the manager accesses the management landing page and will be able to see the following from the dashboard view such as the “Top three staff members with lowest workload”, “Cabin crews more than 40 hours of job assignment”. 

![Image](https://github.com/kyusan93/INF2001_P7-5/assets/97510985/95933905-a41a-4ee9-920e-b28831bd2d36)

4. The “Manager” then clicks on the Allocate Workload tab. The system will display the available route for assigning staff’s weekly schedule. The “Manager” will select the available route, for example, “Singapore -> London”. 


![Image](https://github.com/kyusan93/INF2001_P7-5/assets/97510985/2d95aa80-d3bb-4346-b15c-c7b07dd20c09)

5. The System will display the route information such as the route, flight no, dates, flight model and allocation status. The “Manager” will then click on the allocation status not assigned. 

![Image](https://github.com/kyusan93/INF2001_P7-5/assets/97510985/238b5d10-e372-4bcb-9b8a-0f5fee99b1d6)

6. This displays staff that are available such as the staff name and roles. The “Manager” will then click on the allocation status “Not Assigned” highlighted in yellow. 

![Image](https://github.com/kyusan93/INF2001_P7-5/assets/97510985/d0d16d04-64d6-4152-ac4d-4ccb1dd319f1)


7. The “Manager” will then allocate the required number of staffs for the flight. 

![Image](https://github.com/kyusan93/INF2001_P7-5/assets/97510985/5c2cc756-f359-4aba-b5aa-477ef2755dd8)

8. Alternate Scenarios: If the “Manager” selects more than the required crew, the system will prompt the manager with “YOU HAVE SELECTED MORE THAN REQURIED CREWS”. The “Manager” then clicks “Back” and it returns to the work allocation page. 

![Image](https://github.com/kyusan93/INF2001_P7-5/assets/97510985/3b73706a-e516-468f-8d74-aed0d88b4032)


![Image](https://github.com/kyusan93/INF2001_P7-5/assets/97510985/c2358205-d45f-4716-9a1a-156762da5ecd)



9. The “Manager” allocates the required number of staff for the flight, confirms and saves the allocation. The allocation status will change to assigned.


![Image](https://github.com/kyusan93/INF2001_P7-5/assets/97510985/c0728027-db80-47eb-8d47-35f6eafc1f97)


![Image](https://github.com/kyusan93/INF2001_P7-5/assets/97510985/dc365cc4-49ef-4c33-81a2-f4d1e7c87032)


10. Alternative scenario: If the “Manager” clicks the “Back”, it will lead back to the work allocation page. 


![Image](https://github.com/kyusan93/INF2001_P7-5/assets/97510985/58fdbdf3-10b0-42e4-9e68-9b0dbc1ac6f4)

11. Alternative scenario: If the “Manager” clicks the “Cancel”, it will lead back to the allocate workload page. 

![Image](https://github.com/kyusan93/INF2001_P7-5/assets/97510985/345d1e30-5f13-4505-b1ab-a703602af18a)

12. If the “Manager” clicks save, the system will prompt “Cabin Crew Allocation Updated” and initiate the SMS server to send a message to staff on workload allocation status. 

![Image](https://github.com/kyusan93/INF2001_P7-5/assets/97510985/2c21f294-9c79-41d6-ad29-592e7a368e75)

![Image](https://github.com/kyusan93/INF2001_P7-5/assets/97510985/4d9484fb-a227-4a7e-8acf-8c878d8db997)

**Comment by zchewwwww** [comment]
**Cabin Crews** 

1. The “Staff” will login and selects the role “Cabin Crew” 
 

![Image](https://github.com/kyusan93/INF2001_P7-5/assets/97510985/6beae628-b4c8-4bca-a99c-a337ad7e989f)


 

2. It then redirects to the Cabin Crew login page. 
 
 

![Image](https://github.com/kyusan93/INF2001_P7-5/assets/97510985/5594e557-62eb-445b-ad8f-fdd65b6828ad)



 
3. This displays the landing page, where the “Staff” can view the weekly jobs assigned to them. 
 
 

![Image](https://github.com/kyusan93/INF2001_P7-5/assets/97510985/accf07ab-6574-46a7-a538-8066a8057b63)



 
4. “Staff” reviews jobs assigned to them and click on “Reject” job that have been assigned to them. 
 

![Image](https://github.com/kyusan93/INF2001_P7-5/assets/97510985/001f32bf-862d-4f70-8cd3-9bb4cb295556)



5. The system will present a pop-up warning message “PLEASE INFORM AND DISCUSS WITH YOUR SUPERVISOR BEFORE THIS REJECTION IS CONSIDERED COMPLETED”, the “Staff” will click on “Acknowledge” to confirm the warning pop up message. The system sends out a rejection notification to the manager. 
 


![Image](https://github.com/kyusan93/INF2001_P7-5/assets/97510985/4f5c3624-d818-43c1-ae91-710155f18c8a)

 

6. This will bring the “Staff” back to the landing page, where they view the weekly jobs. It can be seen the status changed from “JOB ASSIGNED” to “PENDING REJECT”. 
 
 


![Image](https://github.com/kyusan93/INF2001_P7-5/assets/97510985/4922da56-dfe7-43e4-8671-63c5165ad6d2)


 
Alternative scenario: The “Staff” can add their job preference 5 weeks in advance. 
 


![Image](https://github.com/kyusan93/INF2001_P7-5/assets/97510985/2e18143e-6186-4740-bfd9-fc5a97abccbe)


Alternative scenario: An error message is displayed to inform the “Staff” that their rejection was submitted after the deadline. 
 
 

![Image](https://github.com/kyusan93/INF2001_P7-5/assets/97510985/a05ad38a-d534-4e84-bb87-d8e351db3155)



8. The “Staff” will be redirected to the set preference page for the date selected. 
 
 

![Image](https://github.com/kyusan93/INF2001_P7-5/assets/97510985/0321389b-f44c-48a0-ae3b-b51da59da512)



9. The “Staff” will be able to select their preferred route and submit it to the system. The “Staff” will then be redirected to the confirmation page. 
 
 

![Image](https://github.com/kyusan93/INF2001_P7-5/assets/97510985/7a6de0e9-49f8-493b-9012-b21b99209526)



Alternative scenario: If the “Staff” clicks on cancel, they will be brought back to the add job preference page. 
 
 

![Image](https://github.com/kyusan93/INF2001_P7-5/assets/97510985/4b3b7511-b8f0-47e6-993b-dad8a4be92bf)



10. The preferred route will be added to the system. 
 
 

![Image](https://github.com/kyusan93/INF2001_P7-5/assets/97510985/d1487f41-3f66-4c04-be40-3537f651bfcd)

**Comment by zchewwwww** [comment]
**IT Administrators** 

“IT Administrator” selects the role of ‘IT Administrator’. 
 

![Image](https://github.com/kyusan93/INF2001_P7-5/assets/97510985/64e87ff5-0d94-41df-957e-11454e6c4d32)



 
It then redirects to the IT Administrator’s login page. 
 

![Image](https://github.com/kyusan93/INF2001_P7-5/assets/97510985/598e6cf4-f23c-4ef9-86c4-2940245d5599)


 

The “IT Administrator” will be able to view the homepage of all users. The “IT Administrator” clicks on ‘Create Account’ to create new users. 
 
 

![Image](https://github.com/kyusan93/INF2001_P7-5/assets/97510985/affcceeb-ac80-48f5-8f83-da541404fe4b)



 
The “IT Administrator” will enter the staff’s name and select the staff’s role and status. Staff roles will include ‘Managers’ and ‘Steward’/’Stewardess’. 
 

![Image](https://github.com/kyusan93/INF2001_P7-5/assets/97510985/ac267734-dba2-4810-aa70-b460a85167d3)


 

After clicking on ‘Create’, the system will prompt to confirm the details entered. 
 
 

![Image](https://github.com/kyusan93/INF2001_P7-5/assets/97510985/430208a1-339e-435a-aa44-144d8c579c36)



Once the “IT Administrator” selects ‘Save’ in the pop-up message, the user will be brought back to the homepage of all users. The changes will be applied, where the new user “Lancy Low” can be seen (No. 5). 
 
 

![Image](https://github.com/kyusan93/INF2001_P7-5/assets/97510985/097ff0b1-d3e2-4064-b21e-8f85c72a21ef)


 

 
**Alternate Scenarios:** If the “IT Administrator” selects ‘Cancel’ for the system message prompt, the user will be brought back to the homepage with no changes applied. 
 
 

![Image](https://github.com/kyusan93/INF2001_P7-5/assets/97510985/d3f47b61-634e-45d6-adf6-79809266cef5)
