### ISSUE TITLE
3.2.4.1 Create Add Job Preference Page

### ISSUE THREAD

**Issue by kyusan93** [kyusan93/INF2001_P7-5#59]

**Comment by SelenaxPS** [comment]
![Image](https://github.com/kyusan93/INF2001_P7-5/assets/50551855/c494e8fd-7ac6-4546-8060-b1b5f2b47424)



![Image](https://github.com/kyusan93/INF2001_P7-5/assets/50551855/b188f3d0-46b6-499f-ba63-6f984bc7a898)

**Comment by kyusan93** [comment]
Completed
