### ISSUE TITLE
3.2.5.1 Create Staff and Manager users Page

### ISSUE THREAD

**Issue by kyusan93** [kyusan93/INF2001_P7-5#62]

**Comment by cordeliajt** [comment]
The “IT Administrator” will enter the staff’s name and select the staff’s role and status. Staff roles will include ‘Managers’ and ‘Steward’/’Stewardess’. 

![Image](https://github.com/kyusan93/INF2001_P7-5/assets/46913067/a1b6f9ff-4212-4ffe-826e-ff6edc10bafa)

After clicking on ‘Create’, the system will prompt to confirm the details entered. 

![Image](https://github.com/kyusan93/INF2001_P7-5/assets/46913067/15d11069-24fc-4f1e-b377-aab952074c62)

Once the “IT Administrator” selects ‘Save’ in the pop-up message, the user will be brought back to the homepage of all users. The changes will be applied, where the new user “Lancy Low” can be seen (No. 5).


![Image](https://github.com/kyusan93/INF2001_P7-5/assets/46913067/4ef65ed0-c04b-486f-8001-b657aa85b2b2)

Alternate Scenarios: If the “IT Administrator” selects ‘Cancel’ for the system message prompt, the user will be brought back to the homepage with no changes applied. 



![Image](https://github.com/kyusan93/INF2001_P7-5/assets/46913067/06892ff2-b1a4-4326-82c0-59eb79094397)

**Comment by kyusan93** [comment]
Completed
