### ISSUE TITLE
3.3.1 White Box Testing

### ISSUE THREAD

**Issue by kyusan93** [kyusan93/INF2001_P7-5#63]

**Comment by cordeliajt** [comment]
Our White box testing is based on Use Case 3.  

Pseudocode 

 

Code 5 White box testing pseudocode 

Control Flow Graph (CFG) 

 

![Image](https://github.com/kyusan93/INF2001_P7-5/assets/46913067/3667fb43-02ee-48a5-9606-ffef60e75602)



Cyclomatic Complexity 

Based on our CFG, we can derive the cyclomatic complexity as calculated below: 

M = E – N + 2P 

Where: 

M is the cyclomatic complexity, 

E is the number of edges, 

N is the number of nodes, and 

P is the connected components. 

 

We will assume P equals to 1, therefore the formula updated as follows: 

M = E – N + 2(1) 

M = 14 - 12 + 2 

M = 4 

 

Basic Path and Cyclomatic Complexity 



![Image](https://github.com/kyusan93/INF2001_P7-5/assets/46913067/b87a1427-42dd-4efa-b197-d8dc2258c6e5)



Path 1: A - B - C - E - F - G - I - J - E - K - L 
Path 2: A - B - C - E - F - H - I - J - E - K - L 
Path 3: A - B - D - E - F - G - I - J - E - K - L 
Path 4: A - B - D - E - F - H - I - J - E - K - L

**Comment by kyusan93** [comment]
Completed
