### ISSUE TITLE
3.3.2 Black Box Testing

### ISSUE THREAD

**Issue by kyusan93** [kyusan93/INF2001_P7-5#64]

**Comment by claudmeow** [comment]
![Image](https://github.com/kyusan93/INF2001_P7-5/assets/108879146/18b59fe5-2bb5-45b6-bb27-66c9667ce8b7)



![Image](https://github.com/kyusan93/INF2001_P7-5/assets/108879146/08b9d144-a765-4dd1-91f3-d65e08ca5e37)



![Image](https://github.com/kyusan93/INF2001_P7-5/assets/108879146/731923c4-ad16-4041-bdc9-183c4c8a861d)

**Comment by kyusan93** [comment]
Completed
